//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Log_TransactionsTbl
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public string TableName { get; set; }
        public string PrimaryKeyField { get; set; }
        public string FieldName { get; set; }
        public string OldValue { get; set; }
        public string NewValue { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LoggedUser { get; set; }
        public string CustomName { get; set; }
        public Nullable<System.Guid> OperationGUID { get; set; }
        public string OldValueName { get; set; }
        public string NewValueName { get; set; }
    }
}
