//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class back_configtbl
    {
        public int Id { get; set; }
        public int TransferConfirmationPeriod { get; set; }
        public int OrderItemQuantityHoldPeriod { get; set; }
        public int OrderTimeoutPeriod { get; set; }
        public int OrderTimeoutRenewalCount { get; set; }
        public double MainAgentOffersDefaultPercentage { get; set; }
        public double SubAgentOffersDefaultPercentage { get; set; }
        public int CurrencyId { get; set; }
        public int CountryId { get; set; }
        public int PriceTypeId { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public int TransferTimeoutPeriod { get; set; }
        public double SearchRange { get; set; }
        public bool AllowSearchByWorkDomain { get; set; }
        public bool AutomaticallyShowUserOnMap { get; set; }
        public bool RequiredSmsVerification { get; set; }
        public bool AutomaticallyActivateUsers { get; set; }
        public bool AbortAllTransferOnFail { get; set; }
        public bool EnablePickUp { get; set; }
        public bool EnableDelivery { get; set; }
        public Nullable<int> CalculationCurrencyId { get; set; }
        public Nullable<int> PreviewCurrencyId { get; set; }
        public bool LinkCurrencies { get; set; }
        public string ItemParam1Name { get; set; }
        public string ItemParam2Name { get; set; }
        public bool EnableItemParam1 { get; set; }
        public bool EnableItemParam2 { get; set; }
        public bool EnableOrderOffer { get; set; }
        public int GrantPointTypeId { get; set; }
        public bool EnableItemSizeChartImage { get; set; }
        public string PolicyArabicTitle { get; set; }
        public string PolicyEnglishTitle { get; set; }
        public string PolicyArabicDescription { get; set; }
        public string PolicyEnglishDescription { get; set; }
        public string OwnerLogoURL { get; set; }
        public string OwnerArabicTitle { get; set; }
        public string OwnerEnglishTitle { get; set; }
        public string OwnerArabicDescription { get; set; }
        public string OwnerEnglishDescription { get; set; }
        public string OwnerWebsiteURL { get; set; }
        public string OwnerPhoneNumber { get; set; }
        public string OwnerArabicAddress { get; set; }
        public string OwnerEnglishAddress { get; set; }
        public string OwnerEmail { get; set; }
        public Nullable<int> ItemVisitPeriod { get; set; }
        public Nullable<int> ItemBookingEndDate { get; set; }
        public string ImageIndexSplitter { get; set; }
        public Nullable<int> PriceDigitsNumberAfterComma { get; set; }
        public Nullable<bool> SupportCountry { get; set; }
        public Nullable<bool> SupportGovernorate { get; set; }
        public Nullable<bool> SupportCity { get; set; }
        public Nullable<bool> SupportLocation { get; set; }
        public Nullable<bool> SupportBlockNo { get; set; }
        public Nullable<bool> SupportStreet { get; set; }
        public Nullable<bool> SupportBuilding { get; set; }
        public Nullable<bool> SupportFloor { get; set; }
        public Nullable<bool> SupportApartmentNo { get; set; }
        public Nullable<bool> SupportAddressesNote { get; set; }
        public Nullable<bool> CountryIsRequired { get; set; }
        public Nullable<bool> GovernorateIsRequired { get; set; }
        public Nullable<bool> CityIsRequired { get; set; }
        public Nullable<bool> LocationIsRequired { get; set; }
        public Nullable<bool> BlockNoIsRequired { get; set; }
        public Nullable<bool> StreetIsRequired { get; set; }
        public Nullable<bool> BuildingIsRequired { get; set; }
        public Nullable<bool> FloorIsRequired { get; set; }
        public Nullable<bool> ApartmentNoIsRequired { get; set; }
        public Nullable<bool> AddressNoteIsRequired { get; set; }
        public Nullable<bool> HasPoints { get; set; }
    }
}
