//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class BannersTbl
    {
        public int Id { get; set; }
        public string ArabicTitle { get; set; }
        public string EnglishTitle { get; set; }
        public string ImageURL { get; set; }
        public Nullable<System.DateTime> StartShowDate { get; set; }
        public Nullable<System.DateTime> EndShowDate { get; set; }
        public Nullable<bool> HasEndDate { get; set; }
        public bool Disabled { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<int> Type { get; set; }
        public Nullable<int> TypeId { get; set; }
        public Nullable<bool> IsVideo { get; set; }
    }
}
