//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categories_tempTbl
    {
        public int Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string Code { get; set; }
        public int Type { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public Nullable<int> ParentId { get; set; }
        public bool Disabled { get; set; }
        public string Notes { get; set; }
        public string ImageURL { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
