//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComplaintsTbl
    {
        public int Id { get; set; }
        public bool IsComment { get; set; }
        public Nullable<int> ParentId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> ComplaintTypeId { get; set; }
        public Nullable<int> ComplaintStatusId { get; set; }
        public int ReferenceId { get; set; }
        public string Description { get; set; }
        public string ImageURL { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<System.DateTime> ClosingDate { get; set; }
    }
}
