//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountriesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountriesTbl()
        {
            this.ConfigTbl = new HashSet<ConfigTbl>();
            this.CategoryCountriesTbl = new HashSet<CategoryCountriesTbl>();
            this.CountryCurrenciesTbl = new HashSet<CountryCurrenciesTbl>();
            this.GovernoratesTbl = new HashSet<GovernoratesTbl>();
            this.ItemDepartmentImageCountriesTbl = new HashSet<ItemDepartmentImageCountriesTbl>();
            this.ItemsCountriesTbl = new HashSet<ItemsCountriesTbl>();
            this.ItemsTbl = new HashSet<ItemsTbl>();
            this.OffersCountriesTbl = new HashSet<OffersCountriesTbl>();
            this.OrdersTbl = new HashSet<OrdersTbl>();
            this.UsersTbl = new HashSet<UsersTbl>();
        }
    
        public int Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string Code { get; set; }
        public bool ShowInSignUp { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public string PolicyArabicTitle { get; set; }
        public string PolicyEnglishTitle { get; set; }
        public string PolicyArabicDescription { get; set; }
        public string PolicyEnglishDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ConfigTbl> ConfigTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CategoryCountriesTbl> CategoryCountriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CountryCurrenciesTbl> CountryCurrenciesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GovernoratesTbl> GovernoratesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemDepartmentImageCountriesTbl> ItemDepartmentImageCountriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsCountriesTbl> ItemsCountriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsTbl> ItemsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersCountriesTbl> OffersCountriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTbl> OrdersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersTbl> UsersTbl { get; set; }
    }
}
