//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryCurrenciesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CountryCurrenciesTbl()
        {
            this.ItemPricesTbl = new HashSet<ItemPricesTbl>();
            this.OffersDetailsPricesTbl = new HashSet<OffersDetailsPricesTbl>();
        }
    
        public int Id { get; set; }
        public int CountryId { get; set; }
        public int CurrencyId { get; set; }
        public bool Disabled { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    
        public virtual CountriesTbl CountriesTbl { get; set; }
        public virtual CurrenciesTbl CurrenciesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemPricesTbl> ItemPricesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsPricesTbl> OffersDetailsPricesTbl { get; set; }
    }
}
