//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MatjarTestDBEntities : DbContext
    {
        public MatjarTestDBEntities()
            : base("name=MatjarTestDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AgentVisitsTbl> AgentVisitsTbl { get; set; }
        public virtual DbSet<AreasTbl> AreasTbl { get; set; }
        public virtual DbSet<AttributesListDetailsTbl> AttributesListDetailsTbl { get; set; }
        public virtual DbSet<AttributesListDetailValuesTbl> AttributesListDetailValuesTbl { get; set; }
        public virtual DbSet<AttributesListsTbl> AttributesListsTbl { get; set; }
        public virtual DbSet<Audit_Log_Login> Audit_Log_Login { get; set; }
        public virtual DbSet<BannersTbl> BannersTbl { get; set; }
        public virtual DbSet<BarcodesTbl> BarcodesTbl { get; set; }
        public virtual DbSet<BranchesTbl> BranchesTbl { get; set; }
        public virtual DbSet<BrandsDepartmentsTbl> BrandsDepartmentsTbl { get; set; }
        public virtual DbSet<BrandsTbl> BrandsTbl { get; set; }
        public virtual DbSet<CategoriesTbl> CategoriesTbl { get; set; }
        public virtual DbSet<CategoriesTypesTbl> CategoriesTypesTbl { get; set; }
        public virtual DbSet<CitiesTbl> CitiesTbl { get; set; }
        public virtual DbSet<ColorsTbl> ColorsTbl { get; set; }
        public virtual DbSet<CompaniesTbl> CompaniesTbl { get; set; }
        public virtual DbSet<ComplaintStatusTbl> ComplaintStatusTbl { get; set; }
        public virtual DbSet<ComplaintsTbl> ComplaintsTbl { get; set; }
        public virtual DbSet<ComplaintTypeTbl> ComplaintTypeTbl { get; set; }
        public virtual DbSet<ConfigTbl> ConfigTbl { get; set; }
        public virtual DbSet<CountriesTbl> CountriesTbl { get; set; }
        public virtual DbSet<CountryCurrenciesTbl> CountryCurrenciesTbl { get; set; }
        public virtual DbSet<CouponsTbl> CouponsTbl { get; set; }
        public virtual DbSet<CouponTypesTbl> CouponTypesTbl { get; set; }
        public virtual DbSet<CurrenciesTbl> CurrenciesTbl { get; set; }
        public virtual DbSet<CustomColumnsNamesTbl> CustomColumnsNamesTbl { get; set; }
        public virtual DbSet<CustomTablesNamesTbl> CustomTablesNamesTbl { get; set; }
        public virtual DbSet<DaysTbl> DaysTbl { get; set; }
        public virtual DbSet<DeliveryPlacesTbl> DeliveryPlacesTbl { get; set; }
        public virtual DbSet<DeviceRegistrationIdsTbl> DeviceRegistrationIdsTbl { get; set; }
        public virtual DbSet<DevicesLogTbl> DevicesLogTbl { get; set; }
        public virtual DbSet<EducationLevelsTbl> EducationLevelsTbl { get; set; }
        public virtual DbSet<ErrorsLogTbl> ErrorsLogTbl { get; set; }
        public virtual DbSet<ExcelReportsTbl> ExcelReportsTbl { get; set; }
        public virtual DbSet<FakeData> FakeData { get; set; }
        public virtual DbSet<GovernoratesTbl> GovernoratesTbl { get; set; }
        public virtual DbSet<GrantPointTypesTbl> GrantPointTypesTbl { get; set; }
        public virtual DbSet<ItemBookingDaysTbl> ItemBookingDaysTbl { get; set; }
        public virtual DbSet<ItemBookingDayTimesTbl> ItemBookingDayTimesTbl { get; set; }
        public virtual DbSet<ItemBookingStatusTbl> ItemBookingStatusTbl { get; set; }
        public virtual DbSet<ItemBookingsTbl> ItemBookingsTbl { get; set; }
        public virtual DbSet<ItemColorsPricesTbl> ItemColorsPricesTbl { get; set; }
        public virtual DbSet<ItemColorsSizesPricesTbl> ItemColorsSizesPricesTbl { get; set; }
        public virtual DbSet<ItemColorsSizesTbl> ItemColorsSizesTbl { get; set; }
        public virtual DbSet<ItemColorsTbl> ItemColorsTbl { get; set; }
        public virtual DbSet<ItemDepartmentImageCountriesTbl> ItemDepartmentImageCountriesTbl { get; set; }
        public virtual DbSet<ItemDepartmentImagesTbl> ItemDepartmentImagesTbl { get; set; }
        public virtual DbSet<ItemDepartmentsTbl> ItemDepartmentsTbl { get; set; }
        public virtual DbSet<ItemImagesTbl> ItemImagesTbl { get; set; }
        public virtual DbSet<ItemLikesTbl> ItemLikesTbl { get; set; }
        public virtual DbSet<ItemMatchedItemsTbl> ItemMatchedItemsTbl { get; set; }
        public virtual DbSet<ItemPricesTbl> ItemPricesTbl { get; set; }
        public virtual DbSet<ItemQuantitiesTbl> ItemQuantitiesTbl { get; set; }
        public virtual DbSet<ItemRatingsTbl> ItemRatingsTbl { get; set; }
        public virtual DbSet<ItemsCompaniesTbl> ItemsCompaniesTbl { get; set; }
        public virtual DbSet<ItemsCountriesTbl> ItemsCountriesTbl { get; set; }
        public virtual DbSet<ItemSerialsTbl> ItemSerialsTbl { get; set; }
        public virtual DbSet<ItemSeriesTbl> ItemSeriesTbl { get; set; }
        public virtual DbSet<ItemsGovernoratesTbl> ItemsGovernoratesTbl { get; set; }
        public virtual DbSet<ItemSizesPricesTbl> ItemSizesPricesTbl { get; set; }
        public virtual DbSet<ItemSizesTbl> ItemSizesTbl { get; set; }
        public virtual DbSet<ItemsTbl> ItemsTbl { get; set; }
        public virtual DbSet<ItemsUsersTypesTbl> ItemsUsersTypesTbl { get; set; }
        public virtual DbSet<ItemTagsTbl> ItemTagsTbl { get; set; }
        public virtual DbSet<ItemTypeAttributesTbl> ItemTypeAttributesTbl { get; set; }
        public virtual DbSet<ItemTypeDepartmentsTbl> ItemTypeDepartmentsTbl { get; set; }
        public virtual DbSet<ItemTypesTbl> ItemTypesTbl { get; set; }
        public virtual DbSet<ItemWishlistsTbl> ItemWishlistsTbl { get; set; }
        public virtual DbSet<JobsTbl> JobsTbl { get; set; }
        public virtual DbSet<LocationDaysTbl> LocationDaysTbl { get; set; }
        public virtual DbSet<LocationDayTimesTbl> LocationDayTimesTbl { get; set; }
        public virtual DbSet<LocationsTbl> LocationsTbl { get; set; }
        public virtual DbSet<MainBalanceTbl> MainBalanceTbl { get; set; }
        public virtual DbSet<MainBalanceTypesTbl> MainBalanceTypesTbl { get; set; }
        public virtual DbSet<MaintenanceStatusTbl> MaintenanceStatusTbl { get; set; }
        public virtual DbSet<MaintenanceTicketsTbl> MaintenanceTicketsTbl { get; set; }
        public virtual DbSet<NotificationsTbl> NotificationsTbl { get; set; }
        public virtual DbSet<NotificationsTbl_Audit> NotificationsTbl_Audit { get; set; }
        public virtual DbSet<NotificationsTypesTbl> NotificationsTypesTbl { get; set; }
        public virtual DbSet<NotificationsUsersTbl> NotificationsUsersTbl { get; set; }
        public virtual DbSet<OceanCategoryTypesTbl> OceanCategoryTypesTbl { get; set; }
        public virtual DbSet<OceanMatjarCategoriesTbl> OceanMatjarCategoriesTbl { get; set; }
        public virtual DbSet<OceanMatjarColorsTbl> OceanMatjarColorsTbl { get; set; }
        public virtual DbSet<OceanMatjarItemsTbl> OceanMatjarItemsTbl { get; set; }
        public virtual DbSet<OceanMatjarPricesTbl> OceanMatjarPricesTbl { get; set; }
        public virtual DbSet<OceanMatjarSizesTbl> OceanMatjarSizesTbl { get; set; }
        public virtual DbSet<OceanPriceTypesTbl> OceanPriceTypesTbl { get; set; }
        public virtual DbSet<OceanServersTbl> OceanServersTbl { get; set; }
        public virtual DbSet<OffersCompaniesTbl> OffersCompaniesTbl { get; set; }
        public virtual DbSet<OffersCountriesTbl> OffersCountriesTbl { get; set; }
        public virtual DbSet<OffersDetailRulesTbl> OffersDetailRulesTbl { get; set; }
        public virtual DbSet<OffersDetailsColorsSizesPricesTbl> OffersDetailsColorsSizesPricesTbl { get; set; }
        public virtual DbSet<OffersDetailsPricesTbl> OffersDetailsPricesTbl { get; set; }
        public virtual DbSet<OffersDetailsTbl> OffersDetailsTbl { get; set; }
        public virtual DbSet<OffersGovernoratesTbl> OffersGovernoratesTbl { get; set; }
        public virtual DbSet<OffersTbl> OffersTbl { get; set; }
        public virtual DbSet<OffersUsersTypesTbl> OffersUsersTypesTbl { get; set; }
        public virtual DbSet<OfferTypesTbl> OfferTypesTbl { get; set; }
        public virtual DbSet<OrderDetailsNotificationsTbl> OrderDetailsNotificationsTbl { get; set; }
        public virtual DbSet<OrderDetailsOffersDetailsTbl> OrderDetailsOffersDetailsTbl { get; set; }
        public virtual DbSet<OrderDetailsSeriesTbl> OrderDetailsSeriesTbl { get; set; }
        public virtual DbSet<OrderDetailStatusTbl> OrderDetailStatusTbl { get; set; }
        public virtual DbSet<OrderDetailsTbl> OrderDetailsTbl { get; set; }
        public virtual DbSet<OrdersNotificationsTbl> OrdersNotificationsTbl { get; set; }
        public virtual DbSet<OrderStatusTbl> OrderStatusTbl { get; set; }
        public virtual DbSet<OrdersTbl> OrdersTbl { get; set; }
        public virtual DbSet<OrderTypesTbl> OrderTypesTbl { get; set; }
        public virtual DbSet<PaymentMethodsTbl> PaymentMethodsTbl { get; set; }
        public virtual DbSet<PaymentTypeTbl> PaymentTypeTbl { get; set; }
        public virtual DbSet<PositionsTbl> PositionsTbl { get; set; }
        public virtual DbSet<PriceTypesTbl> PriceTypesTbl { get; set; }
        public virtual DbSet<QuantitiesTbl> QuantitiesTbl { get; set; }
        public virtual DbSet<RequestsTbl> RequestsTbl { get; set; }
        public virtual DbSet<ResourcesTbl> ResourcesTbl { get; set; }
        public virtual DbSet<SessionsTbl> SessionsTbl { get; set; }
        public virtual DbSet<SizesGroupsTbl> SizesGroupsTbl { get; set; }
        public virtual DbSet<SizesTbl> SizesTbl { get; set; }
        public virtual DbSet<StoriesTbl> StoriesTbl { get; set; }
        public virtual DbSet<StoryDepartmentsTbl> StoryDepartmentsTbl { get; set; }
        public virtual DbSet<StoryDetailsTbl> StoryDetailsTbl { get; set; }
        public virtual DbSet<StyleActionsTbl> StyleActionsTbl { get; set; }
        public virtual DbSet<StyleDetailsImagesTbl> StyleDetailsImagesTbl { get; set; }
        public virtual DbSet<StyleDetailsItemsTbl> StyleDetailsItemsTbl { get; set; }
        public virtual DbSet<StyleDetailsTbl> StyleDetailsTbl { get; set; }
        public virtual DbSet<StylesTbl> StylesTbl { get; set; }
        public virtual DbSet<StyleTagsTbl> StyleTagsTbl { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TagsTbl> TagsTbl { get; set; }
        public virtual DbSet<TagsTypesTbl> TagsTypesTbl { get; set; }
        public virtual DbSet<tmp__NotificationsTbl_0> tmp__NotificationsTbl_0 { get; set; }
        public virtual DbSet<TransferMethodsTbl> TransferMethodsTbl { get; set; }
        public virtual DbSet<TransferStatusTbl> TransferStatusTbl { get; set; }
        public virtual DbSet<TransfersTbl> TransfersTbl { get; set; }
        public virtual DbSet<UnitsTbl> UnitsTbl { get; set; }
        public virtual DbSet<UsageDataTbl> UsageDataTbl { get; set; }
        public virtual DbSet<UserColumnsTbl> UserColumnsTbl { get; set; }
        public virtual DbSet<UserColumnsTemplatesTbl> UserColumnsTemplatesTbl { get; set; }
        public virtual DbSet<UserCompaniesTbl> UserCompaniesTbl { get; set; }
        public virtual DbSet<UserExcludedColumnsTbl> UserExcludedColumnsTbl { get; set; }
        public virtual DbSet<UserGiftsExceptionsTbl> UserGiftsExceptionsTbl { get; set; }
        public virtual DbSet<UserGiftsRulesTbl> UserGiftsRulesTbl { get; set; }
        public virtual DbSet<UserProfileColumnsTbl> UserProfileColumnsTbl { get; set; }
        public virtual DbSet<UsersAddressesTbl> UsersAddressesTbl { get; set; }
        public virtual DbSet<UsersCouponTbl> UsersCouponTbl { get; set; }
        public virtual DbSet<UserSendExceptionsTbl> UserSendExceptionsTbl { get; set; }
        public virtual DbSet<UserSendRulesTbl> UserSendRulesTbl { get; set; }
        public virtual DbSet<UserSessionsTbl> UserSessionsTbl { get; set; }
        public virtual DbSet<UsersPermissionsTbl> UsersPermissionsTbl { get; set; }
        public virtual DbSet<UsersPermissionsTemplatesTbl> UsersPermissionsTemplatesTbl { get; set; }
        public virtual DbSet<UsersTbl> UsersTbl { get; set; }
        public virtual DbSet<UsersTypesTbl> UsersTypesTbl { get; set; }
        public virtual DbSet<UserTypeGiftsRulesTbl> UserTypeGiftsRulesTbl { get; set; }
        public virtual DbSet<UserTypeSendRulesTbl> UserTypeSendRulesTbl { get; set; }
        public virtual DbSet<UserTypeWithdrawRulesTbl> UserTypeWithdrawRulesTbl { get; set; }
        public virtual DbSet<UserWithdrawExceptionsTbl> UserWithdrawExceptionsTbl { get; set; }
        public virtual DbSet<UserWithdrawRulesTbl> UserWithdrawRulesTbl { get; set; }
        public virtual DbSet<ViewsTbl> ViewsTbl { get; set; }
        public virtual DbSet<WeeklyShiftDatesTbl> WeeklyShiftDatesTbl { get; set; }
        public virtual DbSet<WeightsTbl> WeightsTbl { get; set; }
        public virtual DbSet<WorkDomainsTbl> WorkDomainsTbl { get; set; }
        public virtual DbSet<Audit_Log_TransactionsTbl> Audit_Log_TransactionsTbl { get; set; }
        public virtual DbSet<back_categoriestbl> back_categoriestbl { get; set; }
        public virtual DbSet<back_configtbl> back_configtbl { get; set; }
        public virtual DbSet<back_itemcolorstbl> back_itemcolorstbl { get; set; }
        public virtual DbSet<back_itemimagestbl> back_itemimagestbl { get; set; }
        public virtual DbSet<back_itemstbl> back_itemstbl { get; set; }
        public virtual DbSet<Categories_tempTbl> Categories_tempTbl { get; set; }
        public virtual DbSet<CategoryCountriesTbl> CategoryCountriesTbl { get; set; }
        public virtual DbSet<dummyItemImages> dummyItemImages { get; set; }
        public virtual DbSet<dummyItems> dummyItems { get; set; }
        public virtual DbSet<faketypes> faketypes { get; set; }
        public virtual DbSet<HacksLogTbl> HacksLogTbl { get; set; }
        public virtual DbSet<itemprices_back> itemprices_back { get; set; }
        public virtual DbSet<itemsbackup> itemsbackup { get; set; }
        public virtual DbSet<NewWeightsTbl> NewWeightsTbl { get; set; }
        public virtual DbSet<test2> test2 { get; set; }
        public virtual DbSet<test3> test3 { get; set; }
        public virtual DbSet<Tmp_OrderDetailsTbl> Tmp_OrderDetailsTbl { get; set; }
        public virtual DbSet<TransfersResultTbl> TransfersResultTbl { get; set; }
        public virtual DbSet<xx> xx { get; set; }
        public virtual DbSet<xx_prices> xx_prices { get; set; }
        public virtual DbSet<xxcom> xxcom { get; set; }
        public virtual DbSet<xxitems> xxitems { get; set; }
    }
}
