//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevicesLogTbl
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string uuid { get; set; }
        public string model { get; set; }
        public string manufacture { get; set; }
        public string version { get; set; }
        public string platform { get; set; }
        public System.DateTime date { get; set; }
        public Nullable<int> lunchcount { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
