//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorsLogTbl
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public string ErrorMessage { get; set; }
        public string Stack { get; set; }
        public string Version { get; set; }
        public string SourcePlatform { get; set; }
        public string SourceFunction { get; set; }
        public string Param { get; set; }
        public string Param2 { get; set; }
    }
}
