//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExcelReportsTbl
    {
        public int Id { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ReportName { get; set; }
        public string ReportURL { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
