//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class FakeData
    {
        public int Id { get; set; }
        public string Size { get; set; }
        public string Color { get; set; }
        public string Model { get; set; }
        public string Barcode { get; set; }
        public Nullable<int> Qty { get; set; }
        public string Name { get; set; }
    }
}
