//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemColorsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemColorsTbl()
        {
            this.ItemColorsPricesTbl = new HashSet<ItemColorsPricesTbl>();
            this.ItemSeriesTbl = new HashSet<ItemSeriesTbl>();
            this.OrderDetailsSeriesTbl = new HashSet<OrderDetailsSeriesTbl>();
            this.OrderDetailsTbl = new HashSet<OrderDetailsTbl>();
        }
    
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int ColorId { get; set; }
        public string ColorImageURL { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public string HexValue { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<int> ItemImageIndex { get; set; }
        public Nullable<bool> Disabled { get; set; }
    
        public virtual ColorsTbl ColorsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemColorsPricesTbl> ItemColorsPricesTbl { get; set; }
        public virtual ItemsTbl ItemsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSeriesTbl> ItemSeriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsSeriesTbl> OrderDetailsSeriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsTbl> OrderDetailsTbl { get; set; }
    }
}
