//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemBookingsTbl
    {
        public int Id { get; set; }
        public int ItemId { get; set; }
        public int UserId { get; set; }
        public System.DateTime VisitDate { get; set; }
        public string Note { get; set; }
        public int ItemBookingStatusId { get; set; }
    
        public virtual ItemBookingStatusTbl ItemBookingStatusTbl { get; set; }
    }
}
