//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationDayTimesTbl
    {
        public int Id { get; set; }
        public Nullable<int> LocationDayId { get; set; }
        public Nullable<System.TimeSpan> DeliveryPeriodFrom { get; set; }
        public Nullable<System.TimeSpan> DeliveryPeriodTo { get; set; }
    
        public virtual LocationDaysTbl LocationDaysTbl { get; set; }
    }
}
