//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OceanMatjarPricesTbl
    {
        public int Id { get; set; }
        public Nullable<int> OceanPriceTypeId { get; set; }
        public Nullable<int> MatjarPriceTypeId { get; set; }
    
        public virtual OceanPriceTypesTbl OceanPriceTypesTbl { get; set; }
        public virtual PriceTypesTbl PriceTypesTbl { get; set; }
    }
}
