//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OceanMatjarSizesTbl
    {
        public int Id { get; set; }
        public string OceanSizeId { get; set; }
        public Nullable<int> MatjarSizeId { get; set; }
    
        public virtual SizesTbl SizesTbl { get; set; }
    }
}
