//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffersTbl()
        {
            this.OffersCompaniesTbl = new HashSet<OffersCompaniesTbl>();
            this.OffersCountriesTbl = new HashSet<OffersCountriesTbl>();
            this.OffersDetailsTbl = new HashSet<OffersDetailsTbl>();
            this.OffersGovernoratesTbl = new HashSet<OffersGovernoratesTbl>();
            this.OffersUsersTypesTbl = new HashSet<OffersUsersTypesTbl>();
            this.OrderDetailsTbl = new HashSet<OrderDetailsTbl>();
        }
    
        public int Id { get; set; }
        public int OfferTypeId { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string Code { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public bool HasEndDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public bool Disabled { get; set; }
        public string Notes { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<bool> HasRequiredPoints { get; set; }
        public Nullable<double> RequiredPoints { get; set; }
        public Nullable<bool> HasRequiredPrice { get; set; }
        public Nullable<double> RequiredPrice { get; set; }
        public Nullable<bool> CanGrantPoints { get; set; }
        public Nullable<int> GrantPointsType { get; set; }
        public Nullable<double> GrantPointsValue { get; set; }
        public Nullable<bool> HasPointsDiscount { get; set; }
        public Nullable<int> PointsDiscountType { get; set; }
        public Nullable<double> PointsDiscountValue { get; set; }
        public Nullable<bool> HasPriceDiscount { get; set; }
        public Nullable<int> PriceDiscountType { get; set; }
        public Nullable<double> PriceDiscountValue { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<bool> HasQuantityOffer { get; set; }
        public Nullable<double> RequiredQuantity { get; set; }
        public Nullable<bool> CanGrantQuantity { get; set; }
        public Nullable<double> GrantQuantity { get; set; }
        public Nullable<int> GrantedQuantityOrderTypeId { get; set; }
        public Nullable<double> MinimumOrderValue { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersCompaniesTbl> OffersCompaniesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersCountriesTbl> OffersCountriesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsTbl> OffersDetailsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersGovernoratesTbl> OffersGovernoratesTbl { get; set; }
        public virtual OfferTypesTbl OfferTypesTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
        public virtual UsersTbl UsersTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersUsersTypesTbl> OffersUsersTypesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsTbl> OrderDetailsTbl { get; set; }
    }
}
