//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersGovernoratesTbl
    {
        public int Id { get; set; }
        public int OfferId { get; set; }
        public int GovernorateId { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    
        public virtual GovernoratesTbl GovernoratesTbl { get; set; }
        public virtual OffersTbl OffersTbl { get; set; }
    }
}
