//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersDetailsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OffersDetailsTbl()
        {
            this.OffersDetailRulesTbl = new HashSet<OffersDetailRulesTbl>();
            this.OffersDetailsColorsSizesPricesTbl = new HashSet<OffersDetailsColorsSizesPricesTbl>();
            this.OffersDetailsPricesTbl = new HashSet<OffersDetailsPricesTbl>();
            this.OrderDetailsOffersDetailsTbl = new HashSet<OrderDetailsOffersDetailsTbl>();
        }
    
        public int Id { get; set; }
        public int OfferId { get; set; }
        public int ItemId { get; set; }
        public bool HasInitQuantity { get; set; }
        public double InitQuantity { get; set; }
        public bool Disabled { get; set; }
        public string Notes { get; set; }
        public Nullable<double> SoldQuantity { get; set; }
        public double RemainingQuantity { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<double> ReservedQuantity { get; set; }
        public bool HasPriceOffer { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<int> ItemColorId { get; set; }
        public Nullable<int> ItemSizeId { get; set; }
    
        public virtual ItemsTbl ItemsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailRulesTbl> OffersDetailRulesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsColorsSizesPricesTbl> OffersDetailsColorsSizesPricesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsPricesTbl> OffersDetailsPricesTbl { get; set; }
        public virtual OffersTbl OffersTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
        public virtual UsersTbl UsersTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsOffersDetailsTbl> OrderDetailsOffersDetailsTbl { get; set; }
    }
}
