//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersDetailsPricesTbl
    {
        public int Id { get; set; }
        public int OfferDetailId { get; set; }
        public int CountryCurrencyId { get; set; }
        public int TypeId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<bool> HasPointsOffer { get; set; }
        public Nullable<int> RequiredPoints { get; set; }
        public Nullable<int> GrantedPoints { get; set; }
    
        public virtual CountryCurrenciesTbl CountryCurrenciesTbl { get; set; }
        public virtual OffersDetailsTbl OffersDetailsTbl { get; set; }
        public virtual PriceTypesTbl PriceTypesTbl { get; set; }
    }
}
