//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OffersDetailRulesTbl
    {
        public int Id { get; set; }
        public Nullable<int> OfferDetailId { get; set; }
        public Nullable<double> ConditionQty { get; set; }
        public Nullable<int> FreeItemId { get; set; }
        public Nullable<double> FreeQty { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<bool> HasDiscount { get; set; }
        public Nullable<bool> HasFreeQty { get; set; }
        public string ArabicTitle { get; set; }
        public string EnglishTitle { get; set; }
        public string Code { get; set; }
    
        public virtual ItemsTbl ItemsTbl { get; set; }
        public virtual OffersDetailsTbl OffersDetailsTbl { get; set; }
    }
}
