//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderDetailsTbl()
        {
            this.OrderDetailsOffersDetailsTbl = new HashSet<OrderDetailsOffersDetailsTbl>();
            this.OrderDetailsSeriesTbl = new HashSet<OrderDetailsSeriesTbl>();
        }
    
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public double Points { get; set; }
        public double Qty { get; set; }
        public string UserNote { get; set; }
        public string AdminNote { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public int QuantityReservationRenewalCount { get; set; }
        public bool HasOffer { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<System.DateTime> OfferStartDate { get; set; }
        public Nullable<bool> OfferHasEndDate { get; set; }
        public Nullable<System.DateTime> OfferEndDate { get; set; }
        public Nullable<int> OfferRequiredPoints { get; set; }
        public Nullable<bool> OfferHasInitQuantity { get; set; }
        public Nullable<double> OfferInitQuantity { get; set; }
        public Nullable<double> OfferRemainingQuantity { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public string Notes { get; set; }
        public Nullable<int> ItemColorId { get; set; }
        public Nullable<int> ItemSizeId { get; set; }
        public string DeliveryAddress { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public Nullable<int> GovernorateId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> OfferPrice { get; set; }
        public Nullable<bool> OfferHasPriceOffer { get; set; }
        public Nullable<bool> OfferHasPointsOffer { get; set; }
        public Nullable<int> PriceCurrencyId { get; set; }
        public Nullable<int> PriceCountryId { get; set; }
        public Nullable<int> PriceTypeId { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public Nullable<bool> IsSeries { get; set; }
        public Nullable<bool> OnRequest { get; set; }
        public Nullable<int> OnRequestDays { get; set; }
        public Nullable<int> OrderDetailStatusId { get; set; }
        public Nullable<int> GrantedPoints { get; set; }
        public Nullable<int> OfferGrantedPoints { get; set; }
    
        public virtual CitiesTbl CitiesTbl { get; set; }
        public virtual GovernoratesTbl GovernoratesTbl { get; set; }
        public virtual ItemColorsTbl ItemColorsTbl { get; set; }
        public virtual ItemSizesTbl ItemSizesTbl { get; set; }
        public virtual ItemsTbl ItemsTbl { get; set; }
        public virtual LocationsTbl LocationsTbl { get; set; }
        public virtual OffersTbl OffersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsOffersDetailsTbl> OrderDetailsOffersDetailsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsSeriesTbl> OrderDetailsSeriesTbl { get; set; }
        public virtual OrdersTbl OrdersTbl { get; set; }
    }
}
