//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTbl()
        {
            this.OrderDetailsTbl = new HashSet<OrderDetailsTbl>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public double RequiredPoints { get; set; }
        public double TotalQty { get; set; }
        public int ItemsCount { get; set; }
        public string UserNote { get; set; }
        public string AdminNote { get; set; }
        public Nullable<int> StatusId { get; set; }
        public string StatusNote { get; set; }
        public Nullable<System.DateTime> DeliveryDate { get; set; }
        public Nullable<System.DateTime> InitDate { get; set; }
        public Nullable<System.DateTime> ShippingDate { get; set; }
        public bool IsPosted { get; set; }
        public Nullable<System.DateTime> PostDate { get; set; }
        public int UserId { get; set; }
        public Nullable<int> DeliveredBy { get; set; }
        public Nullable<int> InitedBy { get; set; }
        public Nullable<int> ShippedBy { get; set; }
        public System.DateTime OrderCreatedDate { get; set; }
        public Nullable<System.DateTime> OrderUpdatedDate { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<bool> HasOrderOffer { get; set; }
        public Nullable<int> OfferId { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public Nullable<decimal> CurrencyEqual { get; set; }
        public Nullable<int> CurrencyCountryId { get; set; }
        public Nullable<double> PointsFromNormalBalance { get; set; }
        public Nullable<double> PointsFromGiftsBalance { get; set; }
        public string AddressDescription { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> UserAddressId { get; set; }
        public Nullable<int> BranchId { get; set; }
        public Nullable<int> DeliveryPlaceId { get; set; }
        public Nullable<int> DeliveryUserId { get; set; }
        public Nullable<int> PaymentTypeId { get; set; }
        public string PaymentSerialNumber { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> GovernorateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string BlockNo { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string ApartmentNo { get; set; }
        public string AddressNote { get; set; }
        public Nullable<System.DateTime> StartDeliveryDate { get; set; }
        public Nullable<int> OrderTypeId { get; set; }
        public Nullable<int> SeriesItemsCount { get; set; }
        public Nullable<double> TotalSeriesQty { get; set; }
        public Nullable<decimal> TotalSeriesPrice { get; set; }
        public Nullable<bool> IsImmediateDelivery { get; set; }
        public Nullable<decimal> DeliveryCost { get; set; }
        public Nullable<System.TimeSpan> DeliveryPeriodFrom { get; set; }
        public Nullable<System.TimeSpan> DeliveryPeriodTo { get; set; }
        public Nullable<System.DateTime> LocationDeliveryDate { get; set; }
        public Nullable<decimal> OrderDiscount { get; set; }
        public Nullable<int> CouponId { get; set; }
        public Nullable<decimal> CouponValue { get; set; }
        public Nullable<decimal> Extras { get; set; }
        public Nullable<bool> HasFreeDelivery { get; set; }
    
        public virtual CountriesTbl CountriesTbl { get; set; }
        public virtual CurrenciesTbl CurrenciesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetailsTbl> OrderDetailsTbl { get; set; }
        public virtual OrderStatusTbl OrderStatusTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
        public virtual UsersTbl UsersTbl1 { get; set; }
        public virtual UsersTbl UsersTbl2 { get; set; }
        public virtual UsersTbl UsersTbl3 { get; set; }
    }
}
