//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetailsSeriesTbl
    {
        public int Id { get; set; }
        public int OrderDetailId { get; set; }
        public Nullable<int> ItemColorId { get; set; }
        public Nullable<int> ItemSizeId { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual ItemColorsTbl ItemColorsTbl { get; set; }
        public virtual ItemSizesTbl ItemSizesTbl { get; set; }
        public virtual OrderDetailsTbl OrderDetailsTbl { get; set; }
    }
}
