//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestsTbl
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int Sender_UserId { get; set; }
        public int Receiver_UserId { get; set; }
        public double Amount { get; set; }
        public string Notes { get; set; }
        public int TransferMethodId { get; set; }
        public string TransferCode { get; set; }
        public int TransferStatusId { get; set; }
        public string PinCode { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    
        public virtual TransferMethodsTbl TransferMethodsTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
        public virtual UsersTbl UsersTbl1 { get; set; }
    }
}
