//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoryDepartmentsTbl
    {
        public int Id { get; set; }
        public int StoryId { get; set; }
        public int DepartmentId { get; set; }
    
        public virtual ItemDepartmentsTbl ItemDepartmentsTbl { get; set; }
        public virtual StoriesTbl StoriesTbl { get; set; }
    }
}
