//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleDetailsImagesTbl
    {
        public int Id { get; set; }
        public Nullable<int> StyleDetailId { get; set; }
        public string ImageURL { get; set; }
        public string WebImageURL { get; set; }
    
        public virtual StyleDetailsTbl StyleDetailsTbl { get; set; }
    }
}
