//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleDetailsTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StyleDetailsTbl()
        {
            this.StyleDetailsImagesTbl = new HashSet<StyleDetailsImagesTbl>();
            this.StyleDetailsItemsTbl = new HashSet<StyleDetailsItemsTbl>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StyleId { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleDetailsImagesTbl> StyleDetailsImagesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleDetailsItemsTbl> StyleDetailsItemsTbl { get; set; }
        public virtual StylesTbl StylesTbl { get; set; }
    }
}
