//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StylesTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StylesTbl()
        {
            this.StyleActionsTbl = new HashSet<StyleActionsTbl>();
            this.StyleDetailsTbl = new HashSet<StyleDetailsTbl>();
            this.StyleTagsTbl = new HashSet<StyleTagsTbl>();
        }
    
        public int Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string ImageURL { get; set; }
        public Nullable<bool> Disabled { get; set; }
        public Nullable<int> StyleTypeId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public string WebImageURL { get; set; }
        public Nullable<bool> ShowItems { get; set; }
        public Nullable<int> Order { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleActionsTbl> StyleActionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleDetailsTbl> StyleDetailsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StyleTagsTbl> StyleTagsTbl { get; set; }
    }
}
