//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleActionsTbl
    {
        public int Id { get; set; }
        public Nullable<int> StyleId { get; set; }
        public Nullable<int> TagId { get; set; }
        public string ImageURL { get; set; }
        public string WebImageURL { get; set; }
        public Nullable<int> Order { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
    
        public virtual StylesTbl StylesTbl { get; set; }
    }
}
