//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class StyleDetailsItemsTbl
    {
        public int Id { get; set; }
        public int StyleDetailId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> ItemColorId { get; set; }
    
        public virtual ItemsTbl ItemsTbl { get; set; }
        public virtual StyleDetailsTbl StyleDetailsTbl { get; set; }
    }
}
