//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class test3
    {
        public int Id { get; set; }
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> SizeGroupId { get; set; }
        public Nullable<int> SizeId { get; set; }
        public int ItemSizeId { get; set; }
        public int PriceTypeId { get; set; }
        public int CountryCurrencyId { get; set; }
        public decimal PriceAdd { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
