//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmp__NotificationsTbl_0
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<int> ToUser { get; set; }
        public string NotificationContent { get; set; }
        public bool Notified { get; set; }
        public string NotificationTitle { get; set; }
        public bool Seen { get; set; }
        public Nullable<int> SourceId { get; set; }
        public Nullable<int> QuantityReservationRenewalCount { get; set; }
        public string FullName { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
