//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tmp_OrderDetailsTbl
    {
        public int Id { get; set; }
        public int OrderId { get; set; }
        public int ItemId { get; set; }
        public double Points { get; set; }
        public double Qty { get; set; }
        public string UserNote { get; set; }
        public string AdminNote { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<int> LoggedUser { get; set; }
    }
}
