//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersTbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UsersTbl()
        {
            this.ItemLikesTbl = new HashSet<ItemLikesTbl>();
            this.ItemRatingsTbl = new HashSet<ItemRatingsTbl>();
            this.ItemsTbl = new HashSet<ItemsTbl>();
            this.ItemsTbl1 = new HashSet<ItemsTbl>();
            this.ItemWishlistsTbl = new HashSet<ItemWishlistsTbl>();
            this.MainBalanceTbl = new HashSet<MainBalanceTbl>();
            this.NotificationsTbl = new HashSet<NotificationsTbl>();
            this.NotificationsUsersTbl = new HashSet<NotificationsUsersTbl>();
            this.OffersDetailsTbl = new HashSet<OffersDetailsTbl>();
            this.OffersDetailsTbl1 = new HashSet<OffersDetailsTbl>();
            this.OffersTbl = new HashSet<OffersTbl>();
            this.OffersTbl1 = new HashSet<OffersTbl>();
            this.OrdersTbl = new HashSet<OrdersTbl>();
            this.OrdersTbl1 = new HashSet<OrdersTbl>();
            this.OrdersTbl2 = new HashSet<OrdersTbl>();
            this.OrdersTbl3 = new HashSet<OrdersTbl>();
            this.RequestsTbl = new HashSet<RequestsTbl>();
            this.RequestsTbl1 = new HashSet<RequestsTbl>();
            this.SessionsTbl = new HashSet<SessionsTbl>();
            this.TransfersTbl = new HashSet<TransfersTbl>();
            this.TransfersTbl1 = new HashSet<TransfersTbl>();
            this.UserCompaniesTbl = new HashSet<UserCompaniesTbl>();
            this.UsersCouponTbl = new HashSet<UsersCouponTbl>();
            this.UsersPermissionsTbl = new HashSet<UsersPermissionsTbl>();
            this.WeeklyShiftDatesTbl = new HashSet<WeeklyShiftDatesTbl>();
        }
    
        public int Id { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string MobileNumber { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int UserType { get; set; }
        public Nullable<int> CompanyId { get; set; }
        public Nullable<bool> CanGrantPoints { get; set; }
        public Nullable<bool> CanTakeOffers { get; set; }
        public bool Disabled { get; set; }
        public Nullable<int> GovernorateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public double TotalSent { get; set; }
        public double TotalReceived { get; set; }
        public double PointsBalance { get; set; }
        public double TotalSent_Waiting { get; set; }
        public double TotalReceived_Waiting { get; set; }
        public string QRCode { get; set; }
        public Nullable<int> PositionId { get; set; }
        public Nullable<int> JobId { get; set; }
        public Nullable<int> WorkDomainId { get; set; }
        public Nullable<int> EducationLevelId { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Nickname { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> YearsOfExperience { get; set; }
        public Nullable<int> StaffCount { get; set; }
        public Nullable<bool> HasVocationalCertificate { get; set; }
        public string Notes { get; set; }
        public string CommercialName { get; set; }
        public string AccessToken { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<double> OrdersPoints { get; set; }
        public Nullable<bool> PermissionFromTemplate { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public Nullable<int> CountryCurrencyId { get; set; }
        public Nullable<int> LocationValidated { get; set; }
        public Nullable<bool> VisibleOnMap { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> GiftsPoints { get; set; }
        public Nullable<int> TotalReceivedGiftsPoints { get; set; }
        public Nullable<int> TotalSentFromGiftsPoints { get; set; }
        public Nullable<int> CurrencyId { get; set; }
        public string MobileCountryCode { get; set; }
        public Nullable<double> OrdersPointsFromGifts { get; set; }
        public string BlockNo { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string ApartmentNo { get; set; }
        public string AddressNote { get; set; }
        public Nullable<int> CurrentBranchId { get; set; }
        public string CardNumber { get; set; }
        public string AccountNumber { get; set; }
        public string CardType { get; set; }
        public string MaritalStatus { get; set; }
        public string ChildCount { get; set; }
        public string Nationality { get; set; }
        public string MobileNumber2 { get; set; }
        public Nullable<bool> FilterByCountry { get; set; }
    
        public virtual CitiesTbl CitiesTbl { get; set; }
        public virtual CompaniesTbl CompaniesTbl { get; set; }
        public virtual CountriesTbl CountriesTbl { get; set; }
        public virtual EducationLevelsTbl EducationLevelsTbl { get; set; }
        public virtual GovernoratesTbl GovernoratesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLikesTbl> ItemLikesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRatingsTbl> ItemRatingsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsTbl> ItemsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemsTbl> ItemsTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemWishlistsTbl> ItemWishlistsTbl { get; set; }
        public virtual JobsTbl JobsTbl { get; set; }
        public virtual LocationsTbl LocationsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MainBalanceTbl> MainBalanceTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationsTbl> NotificationsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationsUsersTbl> NotificationsUsersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsTbl> OffersDetailsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersDetailsTbl> OffersDetailsTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersTbl> OffersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OffersTbl> OffersTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTbl> OrdersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTbl> OrdersTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTbl> OrdersTbl2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersTbl> OrdersTbl3 { get; set; }
        public virtual PositionsTbl PositionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsTbl> RequestsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequestsTbl> RequestsTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SessionsTbl> SessionsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransfersTbl> TransfersTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransfersTbl> TransfersTbl1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserCompaniesTbl> UserCompaniesTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersCouponTbl> UsersCouponTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UsersPermissionsTbl> UsersPermissionsTbl { get; set; }
        public virtual WorkDomainsTbl WorkDomainsTbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WeeklyShiftDatesTbl> WeeklyShiftDatesTbl { get; set; }
    }
}
