//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersCouponTbl
    {
        public int Id { get; set; }
        public int CouponId { get; set; }
        public int UserId { get; set; }
    
        public virtual CouponsTbl CouponsTbl { get; set; }
        public virtual UsersTbl UsersTbl { get; set; }
    }
}
