//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersPermissionsTemplatesTbl
    {
        public int Id { get; set; }
        public int UserTypesId { get; set; }
        public bool CanCreateUsers { get; set; }
        public bool CanDeleteUsers { get; set; }
        public bool CanUpdateUsers { get; set; }
        public bool CanCreateTransfer { get; set; }
        public bool CanUpdateTransfer { get; set; }
        public bool CanDeleteTransfer { get; set; }
        public bool CanTransfer { get; set; }
        public bool UnlimitedTransfer { get; set; }
        public double MaxTransferAmount { get; set; }
        public bool CanCreateOffers { get; set; }
        public bool CanUpdateOffers { get; set; }
        public bool CanDeleteOffers { get; set; }
        public bool CanCreateItems { get; set; }
        public bool CanUpdateItems { get; set; }
        public bool CanDeleteItems { get; set; }
        public bool CanChangeUserPermissions { get; set; }
        public bool CanCreateCities { get; set; }
        public bool CanUpdateCities { get; set; }
        public bool CanDeleteCities { get; set; }
        public bool CanCreateLocations { get; set; }
        public bool CanUpdateLocations { get; set; }
        public bool CanDeleteLocations { get; set; }
        public bool CanCreateCompanies { get; set; }
        public bool CanUpdateCompanies { get; set; }
        public bool CanDeleteCompanies { get; set; }
        public bool CanCreateGovernorates { get; set; }
        public bool CanUpdateGovernorates { get; set; }
        public bool CanDeleteGovernorates { get; set; }
        public bool CanCreatePositions { get; set; }
        public bool CanUpdatePositions { get; set; }
        public bool CanDeletePositions { get; set; }
        public bool CanCreateJobs { get; set; }
        public bool CanUpdateJobs { get; set; }
        public bool CanDeleteJobs { get; set; }
        public bool CanCreateWorkDomains { get; set; }
        public bool CanUpdateWorkDomains { get; set; }
        public bool CanDeleteWorkDomains { get; set; }
        public bool CanCreateEducationLevels { get; set; }
        public bool CanUpdateEducationLevels { get; set; }
        public bool CanDeleteEducationLevels { get; set; }
        public bool CanCreateBrands { get; set; }
        public bool CanUpdateBrands { get; set; }
        public bool CanDeleteBrands { get; set; }
        public bool CanCreateCategories { get; set; }
        public bool CanUpdateCategories { get; set; }
        public bool CanDeleteCategories { get; set; }
        public bool CanCreateColors { get; set; }
        public bool CanUpdateColors { get; set; }
        public bool CanDeleteColors { get; set; }
        public bool CanCreateCountries { get; set; }
        public bool CanUpdateCountries { get; set; }
        public bool CanDeleteCountries { get; set; }
        public bool CanCreateCurrencies { get; set; }
        public bool CanUpdateCurrencies { get; set; }
        public bool CanDeleteCurrencies { get; set; }
        public bool CanCreateItemsGovernorates { get; set; }
        public bool CanUpdateItemsGovernorates { get; set; }
        public bool CanDeleteItemsGovernorates { get; set; }
        public bool CanCreateItemsCompanies { get; set; }
        public bool CanUpdateItemsCompanies { get; set; }
        public bool CanDeleteItemsCompanies { get; set; }
        public bool CanCreateItemsUsersTypes { get; set; }
        public bool CanUpdateItemsUsersTypes { get; set; }
        public bool CanDeleteItemsUsersTypes { get; set; }
        public bool CanCreateOffersGovernorates { get; set; }
        public bool CanUpdateOffersGovernorates { get; set; }
        public bool CanDeleteOffersGovernorates { get; set; }
        public bool CanCreateOffersCompanies { get; set; }
        public bool CanUpdateOffersCompanies { get; set; }
        public bool CanDeleteOffersCompanies { get; set; }
        public bool CanCreateOffersUsersTypes { get; set; }
        public bool CanUpdateOffersUsersTypes { get; set; }
        public bool CanDeleteOffersUsersTypes { get; set; }
        public bool CanCreateOffersDetails { get; set; }
        public bool CanUpdateOffersDetails { get; set; }
        public bool CanDeleteOffersDetails { get; set; }
        public bool CanCreateOrders { get; set; }
        public bool CanUpdateOrders { get; set; }
        public bool CanDeleteOrders { get; set; }
        public bool CanCreateOrderDetails { get; set; }
        public bool CanUpdateOrderDetails { get; set; }
        public bool CanDeleteOrderDetails { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public bool CanCreateSizesGroups { get; set; }
        public bool CanUpdateSizesGroups { get; set; }
        public bool CanDeleteSizesGroups { get; set; }
        public bool CanCreateSizes { get; set; }
        public bool CanUpdateSizes { get; set; }
        public bool CanDeleteSizes { get; set; }
        public bool CanCreateBanners { get; set; }
        public bool CanUpdateBanners { get; set; }
        public bool CanDeleteBanners { get; set; }
        public bool CanCreateItemColors { get; set; }
        public bool CanUpdateItemColors { get; set; }
        public bool CanDeleteItemColors { get; set; }
        public bool CanCreateItemSizes { get; set; }
        public bool CanUpdateItemSizes { get; set; }
        public bool CanDeleteItemSizes { get; set; }
        public bool CanCreateItemImages { get; set; }
        public bool CanUpdateItemImages { get; set; }
        public bool CanDeleteItemImages { get; set; }
        public bool CanUpdateColumnsTemplete { get; set; }
        public bool CanUpdateColumns { get; set; }
        public bool CanCreateItemPrices { get; set; }
        public bool CanUpdateItemPrices { get; set; }
        public bool CanDeleteItemPrices { get; set; }
        public bool CanCreatePriceTypes { get; set; }
        public bool CanUpdatePriceTypes { get; set; }
        public bool CanDeletePriceTypes { get; set; }
        public bool CanCreateUserProfileColumns { get; set; }
        public bool CanUpdateUserProfileColumns { get; set; }
        public bool CanDeleteUserProfileColumns { get; set; }
        public bool CanValidateUserLocation { get; set; }
        public bool CanCreateUserCompanies { get; set; }
        public bool CanUpdateUserCompanies { get; set; }
        public bool CanDeleteUserCompanies { get; set; }
        public bool CanCreateUserTypeTransferRules { get; set; }
        public bool CanUpdateUserTypeTransferRules { get; set; }
        public bool CanDeleteUserTypeTransferRules { get; set; }
        public bool CanCreateUserTransferRules { get; set; }
        public bool CanUpdateUserTransferRules { get; set; }
        public bool CanDeleteUserTransferRules { get; set; }
        public bool CanCreateUserTransferException { get; set; }
        public bool CanUpdateUserTransferException { get; set; }
        public bool CanDeleteUserTransferException { get; set; }
        public bool CanCreateBranches { get; set; }
        public bool CanUpdateBranches { get; set; }
        public bool CanDeleteBranches { get; set; }
        public bool CanCreateItemDepartments { get; set; }
        public bool CanUpdateItemDepartments { get; set; }
        public bool CanDeleteItemDepartments { get; set; }
        public bool CanCreateItemBooking { get; set; }
        public bool CanDeleteItemBooking { get; set; }
    
        public virtual UsersTypesTbl UsersTypesTbl { get; set; }
    }
}
