//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersAddressesTbl
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public string AddressName { get; set; }
        public string AddressDescription { get; set; }
        public Nullable<double> Longitude { get; set; }
        public Nullable<double> Latitude { get; set; }
        public Nullable<int> GovernorateId { get; set; }
        public Nullable<int> CityId { get; set; }
        public string BlockNo { get; set; }
        public string Street { get; set; }
        public string Building { get; set; }
        public string Floor { get; set; }
        public string ApartmentNo { get; set; }
        public string AddressNote { get; set; }
        public Nullable<int> CountryId { get; set; }
        public Nullable<int> LocationId { get; set; }
    }
}
