//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewsTbl
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<int> ReferenceId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> ReferenceType { get; set; }
    }
}
