//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class xx
    {
        public int Id { get; set; }
        public int UserTypeId { get; set; }
        public string TableName { get; set; }
        public Nullable<bool> MobileMode { get; set; }
        public string ColumnName { get; set; }
        public int ColumnOrder { get; set; }
        public Nullable<double> ColumnWidth { get; set; }
    }
}
