//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataServiceLayer.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class xxitems
    {
        public int Id { get; set; }
        public string ArabicName { get; set; }
        public string EnglishName { get; set; }
        public string Code { get; set; }
        public string ArabicDescription { get; set; }
        public string EnglishDescription { get; set; }
        public int BrandId { get; set; }
        public int CountryId { get; set; }
        public int DefaultPriceTypeId { get; set; }
        public double RequiredPoints { get; set; }
        public Nullable<double> GrantedPoints { get; set; }
        public bool Disabled { get; set; }
        public string Notes { get; set; }
        public string ImageURL { get; set; }
        public int CreatedBy { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> LoggedUser { get; set; }
        public string Param1 { get; set; }
        public string Param2 { get; set; }
        public Nullable<bool> IsWholeSale { get; set; }
        public string SizeImageURL { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<int> ItemTypeId { get; set; }
        public Nullable<int> ItemDepartmentId { get; set; }
        public Nullable<bool> HasStartDateBooking { get; set; }
        public Nullable<System.DateTime> StartDateBooking { get; set; }
        public Nullable<bool> HasEndDateBooking { get; set; }
        public Nullable<System.DateTime> EndDateBooking { get; set; }
        public Nullable<bool> OnRequest { get; set; }
        public string OnRequestArabicMessage { get; set; }
        public string OnRequestEnglishMessage { get; set; }
        public Nullable<int> OnRequestDays { get; set; }
        public string ItemURL { get; set; }
        public string ArabicTitle { get; set; }
        public string EnglishTitle { get; set; }
        public Nullable<bool> ShowCarouselInItemsList { get; set; }
        public Nullable<bool> ShowDescriptionInItemsList { get; set; }
    }
}
